spring.application.name=hotel-price-follower
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT}

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.jdbc.batch_size=40
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

scrape.schedule.cron=0 0 12 * * ?
scrape.schedule.zone=Europe/Helsinki

jwt.secret=${JWT_SECRET}
jwt.expire-time=${JWT_EXPIRATION}

cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
